### ISSUE TITLE
How to block swipe until some details are not entered?

### ISSUE THREAD

**Issue by imueed** [Ramotion/paper-onboarding#100]
Hi,
I'm looking to block the swipe to the next screen until the user enters some information like Nickname etc. Is there a way I could achieve that?
Also, I need a way to change the color of the page slider at the bottom? Could that be done?

A quick response would be highly appreciated.
Thanks

**Comment by 0ber** [comment]
for change page slider color use https://github.com/Ramotion/paper-onboarding/blob/master/Source/PaperOnboardingDataSource.swift#L54

for disable gestures: 
`onboarding.gestureControl?.swipeRight.isEnabled = false`
`onboarding.gestureControl?.swipeLeft.isEnabled = false`
