### ISSUE TITLE
How to change color of little circle on bottom of view

### ISSUE THREAD

**Issue by Mike4ftv** [Ramotion/paper-onboarding#102]
Hi,
Is there any method or something else to change color of little circle in bottom of each view of the on boarding flow ? this too clear for me and I don't find any solution...
KR

**Comment by Adaxi-Cat** [comment]
hello，sir，now i have a need，the color need to be gradient，but i have a try ,fail, can you help me  by using this sample ?

**Comment by 0ber** [comment]
use `func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) ` delegate method to change title color
`
func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {
item.titleLabel.textColor = ...
}
`

look readme: https://github.com/Ramotion/paper-onboarding#configuring-content-item

**Comment by 0ber** [comment]
for change circle in page view user this method https://github.com/Ramotion/paper-onboarding/blob/master/Source/PaperOnboardingDataSource.swift#L54
