### ISSUE TITLE
add action button in view

### ISSUE THREAD

**Issue by chetandobariya** [Ramotion/paper-onboarding#108]
[FEATURE REQUEST]

can we add action button in onboarding view?
It would be nice if we can configure UIButton in onboarding Info object.

**Comment by Sonali2009** [comment]
Yes, It works, add the following code after adding constraints to onboarding -  
let button = UIButton(frame: CGRect(x: homeScreenView.frame.size.width - 75, y: 50, width: 75, height: 60))
        button.setTitle("Skip", for: .normal)
        button.setTitleColor(UIColor.white, for: .normal)
        button.addTarget(self, action: #selector(self.buttonTapped), for: .touchUpInside)
        onboarding.addSubview(button)
