### ISSUE TITLE
Repositioning Image View in Onboarding Item

### ISSUE THREAD

**Issue by matthewharrilal** [Ramotion/paper-onboarding#109]
Wondering if there is a way to change the position of the image view present in each onboarding screen.

#### Why?
Want to us onboarding screens to collect user information such as email, username, and password, therefore, to make room for the text fields I want to change the y position of the image view!

**Comment by 0ber** [comment]
Yes, you can fork the repo, and change `ImageView` layout look for this https://github.com/Ramotion/paper-onboarding/blob/master/Source/OnboardingContentView/Item/OnboardingContantViewItem.swift#L187-L189
