### ISSUE TITLE
Tap on screen / pager circle to go next or back (prev)

### ISSUE THREAD

**Issue by mixdesign** [Ramotion/paper-onboarding#11]
I think must have actions for non-experienced users.

**Comment by 0ber** [comment]
You can add UITapGestureRecognizer and call method `func currentIndex(index: Int, animated: Bool)`

**Comment by av0c0der** [comment]
@mixdesign added in version [`2.2`](https://github.com/Ramotion/paper-onboarding/releases/tag/2.2)
