### ISSUE TITLE
Incorrect argument label in call (have 'itemsCount:', expected 'coder:')

### ISSUE THREAD

**Issue by thunpisit** [Ramotion/paper-onboarding#110]
From the example code I try running, and it get error at this line of code:

`let onboarding = PaperOnboarding(itemsCount: 3)`

Saying: `Incorrect argument label in call (have 'itemsCount:', expected 'coder:')`. but when I change from itemsCount to coder it yell another error. I'm not sure that should I change or I am missing something?

I looked further inside the framework and appear to be in this area 

```
init(itemsCount _: Int, delegate: OnboardingContentViewDelegate) {
        self.delegate = delegate
        super.init(frame: CGRect.zero)

        commonInit()
    }

    required init?(coder _: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by 0ber** [comment]
PaperOnboarding does not have `init(itemsCount,...)` method
look to the code https://github.com/Ramotion/paper-onboarding/blob/master/Source/PaperOnboarding.swift#L67-L82

To set pages, you must use delegate and datasource methods

**Comment by thunpisit** [comment]
@0ber In the README on https://github.com/Ramotion/paper-onboarding you guys have `let onboarding = PaperOnboarding(itemsCount: 3)` tho?
