### ISSUE TITLE
Which swift version does it use?

### ISSUE THREAD

**Issue by lokisama** [Ramotion/paper-onboarding#112]
--My Env
xcode: 10.2.1
swift: 5
pod: 1.7.5

-- Error Msg:
Type 'String' has no member 'forwards'
in PageViewItem.swift and FillAnimationView.swift

**Comment by igork-ramotion** [comment]
@lokisama current Swift version is 5.1. But it shouldn't be a problem
`forwards` is a value of CAMediaTimingFillMode, it is not a string and available from iOS 2.0

Please take a look at documentations:
https://developer.apple.com/documentation/quartzcore/camediatimingfillmode/1427658-forwards

It seems that you have incorrect error output for some reason.  Please check it in empty project or provide more information
