### ISSUE TITLE
Swiping the onboarding not working in iOS 13

### ISSUE THREAD

**Issue by NanoMeko** [Ramotion/paper-onboarding#116]

**Comment by BillBunting** [comment]
I can confirm the same problem. But, there is an easy fix for iOS 13. If you set the modal presentation style on the containing view controller to Full Screen, it will swipe correctly.  The default presentation is now page sheet, not full screen, which does not work with the current version of paper-onboarding. 

Objective C
```
vc.modalPresentationStyle = UIModalPresentationFullScreen;
```

Swift 
```
vc.modalPresentationStyle = .FullScreen
```

https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/fullscreen

**Comment by aheze** [comment]
I made a pull request that fixes this, without forcing presentation in full screen.
https://github.com/Ramotion/paper-onboarding/pull/124#issue-445602674.
