### ISSUE TITLE
Error when adding Image from Asset in Xcode 11.1 IOS 13 (CUICatalog: Invalid asset name supplied: '')

### ISSUE THREAD

**Issue by IvanLipotan** [Ramotion/paper-onboarding#117]
Hi, I wanted to set the image into the ONBoardingItemInfo. However, I am adding this function informationImage: UIImage(named: "Page1")!. My Asset file image has called "Page1"). I guess this should be the correct code to call the specific image. But the error is  CUICatalog: Invalid asset name supplied: ''". Do you know how to fix this problem? Thank you

2019-10-18 10:37:54.442804+0700 CollaborationApp[2673:92187] [framework] CUICatalog: Invalid asset name supplied: ''

**Comment by igork-ramotion** [comment]
It should work fine. Please provide source code if you still need help
