### ISSUE TITLE
Cannot add custom views like buttons that need to recognize gestures

### ISSUE THREAD

**Issue by saheljalal** [Ramotion/paper-onboarding#119]
The `PaperOnboarding` class has a `GestureControl` view that gets added as the last subview and spans the entire content area and swallows gestures.  Adding any buttons or subviews cannot get taps. Is there a workaround or can you update to support this properly?

**Comment by saheljalal** [comment]
Found workaround:
Add tap gesture recognizer, translate to button and hit test that. Unfortunately, you cannot use the standard `addTarget` API with the current design AFAIK.

**Comment by igork-ramotion** [comment]
If you want you can replace logic from `GestureControl` into `PaperOnboarding` view, in that case there will be no problems with any subviews
