### ISSUE TITLE
Include the pageIcon image view and circle in OnboardingContentViewItem

### ISSUE THREAD

**Issue by tciuro** [Ramotion/paper-onboarding#120]
Some background colors completely hide the pageIcon. Using `onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int)` I can easily tint the image icon, but the pageIcon is out of reach with the given API.

ER: Include the pageIcon image view and circle in OnboardingContentViewItem so that they can be tinted appropriately.

**Comment by igork-ramotion** [comment]
Please take a look at OnboardingItemInfo you already can use your image as `pageIcon`. Also you can use data source method `func onboardingPageItemColor(at index: Int) -> UIColor` to update color.

**Comment by tciuro** [comment]
Ah yes! Thank you! Works like a charm! 👍🏻🙏🏻
