### ISSUE TITLE
Can't get Onboarding Configuration Item to fire - ideas?

### ISSUE THREAD

**Issue by SteveBlackUK** [Ramotion/paper-onboarding#121]
Love the onboarding flow! Only thing is I'd love to tweak the spacing for the description test, but can't get onboardingConfigurationItem() to fire.

Is anyone able to share an example of how they implemented it?

Thanks!

**Comment by igork-ramotion** [comment]
@SteveBlackUK Hey!) Please check v6.1.5 now you can change description offset by using `item.descriptionCenterConstraint` in 
`func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int)`  
Thank You for finding this bug!

**Comment by SteveBlackUK** [comment]
@igork-ramotion - thanks!  is there a way to change description offset vs. left and right sides?  E.g., add spacing vs. safe area?  I can't seem to find anything that lets me do that?

**Comment by SteveBlackUK** [comment]
managed to find it: descriptionPadding

Example use for others:
  OnboardingItemInfo(informationImage: UIImage(named: "brandWrench")!,
                               title: "Build Challenges",
                               description: "Coming soon....the ability to build and publish your own challenges!",
                               pageIcon: UIImage(named: "brandWrench")!,
                               color: UIColor(named: "brandLightGrey")!,
                               titleColor: UIColor(named: "brandNavyBlue")!,
                               descriptionColor: UIColor(named: "brandNavyBlue")!,
                               titleFont: .systemFont(ofSize: 34, weight: .semibold),
                               descriptionFont: .systemFont(ofSize: 18, weight: .regular),
                               descriptionLabelPadding: 40),
