### ISSUE TITLE
Description label is being cut off when run on a physical device

### ISSUE THREAD

**Issue by eashan-mathur** [Ramotion/paper-onboarding#122]
When I am running the project on the simulator, everything works fine, but when run on a physical device, my description label label is only one line with the rest truncated ("example tex..."). Any ideas why?

Also any insight on setting constraints for a button? doing so makes the button either dissappear or show at an unwanted location.

Thanks!!

**Comment by igork-ramotion** [comment]
@eash4 Hey, just checked on device and for me there is no truncation problem. Please be sure that you do not change default setting for description label. By default description label has `numberOfLines = 0` so it should support multiline mode, but you can change this with delegate method
 
`func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int)` 

About second question. We do not support this feature, you can only adjust bottom offset by changing `pageViewBottomConstant`
