### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by Francis220** [Ramotion/paper-onboarding#129]
I am getting the error "Type of expression is ambiguous without more context" on the return part of the onboardingItem function. I'm on Xcode 12.

**Comment by igork-ramotion** [comment]
@Francis360-creator Hey!) Please take a look at the Demo project, hope it will help you. I just tried to run code at Xcode 12 and it works fine.
Or you can provide code chunk that describes you problem, and reopen this issue
