### ISSUE TITLE
Swipe last tab to open HomeVC instead of using skip button

### ISSUE THREAD

**Issue by Kalianey** [Ramotion/paper-onboarding#14]
Hi, 
I am trying to use your delegate methods to open homevc once the user is on the last tab and swipe right, but it doesn't work. How can I swipe the last tab to perform a segue?

**Comment by chug2k** [comment]
#13 is the same question :). Use the delegate: https://cdn.rawgit.com/Ramotion/paper-onboarding/master/docs/Protocols/PaperOnboardingDelegate.html

**Comment by Kalianey** [comment]
But like I said I am using the delegate, but it doesn't recognize the swipe right once you are on the last index, so the swipe gesture do not allow to open the next controller. So none of the methods allow to do that. If I'm wrong could you show me how to use it?

**Comment by chug2k** [comment]
One terrible hack is to add one extra page, and transition from there.

**Comment by jeryRazakarison** [comment]
Hi, I need it to. The solution is to create an optional delegate method that would be called if the user tries to swipe right when in the last page. (currently, it does nothing).

I'm forking, and will PR asap :)
