### ISSUE TITLE
Crash on setting up the delegate

### ISSUE THREAD

**Issue by sundarsan** [Ramotion/paper-onboarding#15]
Any of the method i follow app is getting crashed with fatal error 

on this line "    guard case let dataSource as PaperOnboardingDataSource = self.dataSource else {
"

`  private func createItemsInfo() -> [OnboardingItemInfo] {
    guard case let dataSource as PaperOnboardingDataSource = self.dataSource else {
      fatalError("set dataSource")
    }

```
var items = [OnboardingItemInfo]()
for index in 0..<itemsCount {
  let info = dataSource.onboardingItemAtIndex(index)
  items.append(info)
}
return items
```

  }

}`

any clue , please find the attached screenshot of my crashLog 
![screen shot 2016-06-22 at 5 04 47 pm](https://cloud.githubusercontent.com/assets/839582/16265182/876a02dc-389b-11e6-8d7d-e5122153463d.png)

**Comment by goldenstatewarriors** [comment]
I'm also having this issue. Any luck?

**Comment by 0ber** [comment]
need set dataSource look readme.md

**Comment by goldenstatewarriors** [comment]
The data source is set in the storyboard but I still received this error. Also tried it with the programmatic alternative but I received the same error.

**Comment by goldenstatewarriors** [comment]
I tried this and unfortunately I got the same error - tried with code and
in storyboard.

On Mon, Jul 11, 2016 at 2:45 AM, Alex notifications@github.com wrote:

> need set dataSource look readme.md
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Ramotion/paper-onboarding/issues/15#issuecomment-231654232,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATaEIrX-CJgn9CSeg1I3ClR5K_g87V6-ks5qUeaKgaJpZM4I7rmH
> .

## 

_Justin Bobo_
Vanderbilt University

**Comment by 0ber** [comment]
@goldenstatewarriors  Do you use CocoaPods or Carthage ?

**Comment by goldenstatewarriors** [comment]
Cocoapods

**Comment by goldenstatewarriors** [comment]
I got it to work - thanks!

**Comment by sundarsan** [comment]
@goldenstatewarriors  would like to know how you fixed this issue

**Comment by petripartanen** [comment]
Make sure your datasource conforms to PaperOnboardingDataSource protocol.

**Comment by m2jobe** [comment]
I still get the error even though the datasource conforms to the procotol, what change did you make @petripartanen

**Comment by ooii** [comment]
Having the same issue and would be happy to know how it has been fixed.
