### ISSUE TITLE
Adding Image and Custom Its Size

### ISSUE THREAD

**Issue by riyanpratamap** [Ramotion/paper-onboarding#17]
Hi,
I have two question here, 
First, Is it possible to add image/UIView under its title? And how to custom its icon size?
I thought something like add/change some value in `onboardingConfigurationItem`

Thank you anyway, it is really great library!

**-- edited**
I can add subview under its title inside `onboardingConfigurationItem`. My question remains: How to custom its icon size? Thank you so much!

**Comment by ikolpachkov** [comment]
Please take a look at [c6cc411]
