### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by mohpor** [Ramotion/paper-onboarding#18]
As Xcode 8 and Swift 3 release becoming imminent, do you have any plans for updating this library for that?

~~P.S.: I have already started the PR, it's way too complicated for me!~~ Done

**Comment by mohpor** [comment]
Hey guys, @ober01 , @Juriv 

It seems nobody cares about Swift 3.0 release around here. I think you guys are busy updating your projects to Xcode 8.0 compatible versions. 

~~I have tried to upgrade this framework to support Swift 3.0 but I'm facing a vicious error which I cannot reproduce outside this project. Can anyone help solving it and add official Swift 3.0 support to paper-onboarding?~~ Done

If interested, please clone [my fork](https://github.com/mohpor/paper-onboarding/tree/Swift3) and try to compile it. There is a problem with [`>>>-`](https://github.com/mohpor/paper-onboarding/blob/Swift3/Source/Helpers/ConstraintsHalper.swift#L24) operator which I can't solve.

More context: [Swift 3 Generic infix operator error](http://stackoverflow.com/questions/39204317/swift-3-generic-infix-operator-error)

Thanks,
M.

**Comment by digidhamu** [comment]
Could you please advise on Swift 3 support.

**Comment by mohpor** [comment]
It seems like nobody cares about this lib @ Remotion! 
~~If I can't solve the problem with the `>>>-` operator, I'm going to release them with a simpler function form and get rid of the operator's use altogether! Is's only 18 places and I can easily replace them.~~ Used the operator.

Is everybody onboard with that?!

**Comment by yichengsun** [comment]
@mohpor fine with me, what's the progress of the fork?

**Comment by mohpor** [comment]
@yichengsun @dhamukrish and others,
I have finished the conversion to Swift 3.0
Everything runs smoothly now.
Not sure when it'll be merged.
Checkout #19 

use this until it is merged:

``` ruby
pod 'paper-onboarding', :git => 'https://github.com/mohpor/paper-onboarding.git', :branch => 'Swift3.0'
```

Cheers,
Happy coding
