### ISSUE TITLE
iOS 8 Compatibility

### ISSUE THREAD

**Issue by Alex293** [Ramotion/paper-onboarding#28]
Hi,

Was wondering which part of the lib require iOS 9 (as stated in cocoapods or event 10 on GitHub) as I plan to extend my app compatibility to iOS 8. Is there just on or two things I should try to port or is it simply not possible without huge efforts ?

**Comment by masterfego** [comment]
Hi, 
I agree with Alex. So many devices run on iOS 8. I think you have to change the minimum deployment target to 8. Many big libraries use Swift 3 and are compatible with iOS 8

**Comment by av0c0der** [comment]
Currently `PaperOnboarding` supports iOS 8.0
