### ISSUE TITLE
Add Control

### ISSUE THREAD

**Issue by scinfu** [Ramotion/paper-onboarding#34]
I'm trying to ad a control like stepper or UIDatePicker to create a tutorial + setup but when i add the view above image view but the gesture view block interactions to the picker .

How to avoid this problem ? any idea ?

my code:

```
let picker = UIDatePicker()
        picker.datePickerMode = .date
        picker.translatesAutoresizingMaskIntoConstraints = false
        item.addSubview(picker)
        let copy = item.imageView!
        item.addConstraints([
            NSLayoutConstraint(item: picker, attribute: .leading, relatedBy: .equal, toItem: copy, attribute: .leading, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: picker, attribute: .trailing, relatedBy: .equal, toItem: copy, attribute: .trailing, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: picker, attribute: .top, relatedBy: .equal, toItem: copy, attribute: .top, multiplier: 1, constant: 0),
            NSLayoutConstraint(item: picker, attribute: .bottom, relatedBy: .equal, toItem: copy, attribute: .bottom, multiplier: 1, constant: 0)
            ])
```

and i tried also to move to front the subview but the gestures do not work

`item.superview?.superview?.bringSubview(toFront: item.superview!)`

**Comment by Droppix** [comment]
Hi,

The problem come from the "PaperOnboarding" view. This class have a view "GestureControl" below all views, and all controls added don't have focus.

Here is a solution:
`

           fileprivate func commonInit() {
			
			...

			//gestureControl = GestureControl(view: self, delegate: self)
			let swipeLeft = UISwipeGestureRecognizer(target: self, action: #selector(GestureControl.swipeHandler(_:)))
			swipeLeft.direction = .left
			addGestureRecognizer(swipeLeft)

			let swipeRight = UISwipeGestureRecognizer(target: self, action: #selector(GestureControl.swipeHandler(_:)))
			swipeRight.direction = .right
			addGestureRecognizer(swipeRight)

			...
		}

		@objc dynamic func swipeHandler(_ gesture: UISwipeGestureRecognizer) {
		    self.gestureControlDidSwipe(gesture.direction)
		}

`
