### ISSUE TITLE
Can't use paper-onboarding

### ISSUE THREAD

**Issue by johnnywhisker** [Ramotion/paper-onboarding#35]
I'm create new project with Xcode 8.2.1 ( using Swift 3 ) and using paper-onboarding 2.0.1. I can't use paper-onboarding. It said that " No such module 'PaperOnboarding' ". What should I do ?

**Comment by robpeach** [comment]
I get the same error - Added as per the instructions.

Perhaps need to add it to your bridging header file?

**Comment by mariobento** [comment]
http://stackoverflow.com/a/36079426

^^ this worked for me

**Comment by TheGreenGentleman** [comment]
Same thing to me, added import PaperOnboarding but I still get "No such module 'PaperOnboarding' "

I used CocoaPods and running on xCode 8.2.1

**Comment by evanhzh** [comment]
same here.

**Comment by rainhut** [comment]
Same here

**Comment by rainhut** [comment]
Found the problem. The module name is paper_onboarding  

So use import paper_onboarding

A good practice would be to name the module PaperOnboarding

**Comment by lexuanquynh** [comment]
thanks

**Comment by caloon** [comment]
Renaming the module to "PaperOnboarding" for Swift would make sense imo as it's very "unswifty" at the moment

**Comment by thuythuyntt** [comment]
@mariobento thanks a lot! :3

**Comment by thuythuyntt** [comment]
To use PaperOnboarding lib, requested platform is iOS 10.0+ and Xcode 9
