### ISSUE TITLE
 Use of undeclared type 'PaperOnboardingDataSource' , PaperOnboardingDelegate 

### ISSUE THREAD

**Issue by anand-y** [Ramotion/paper-onboarding#36]
I am using swift 2.3 in  my project 
I installed pod version 1.1.3
After successful installation of pods when i open up project.xcworkspace
i get the following errors

 Use of undeclared type 'PaperOnboardingDataSource' 
 Use of undeclared type  PaperOnboardingDelegate 
Any suggestions for swift version 2.3
Please help

**Comment by av0c0der** [comment]
@yadavanand did you fixed your issue? If no, it seems like you opened project instead of workspace.

**Comment by mdzahedhossain** [comment]
Add paper_onboarding.framework to the list of "Link Binary with Libraries" and that import "paper_onboarding" in your VC.

**Comment by anthonyylee** [comment]
Is it `import paper_onboarding` or `import PaperOnboarding`. Tutorial I was following used the 2nd one, but my Xcode gives me an error when I do so.
