### ISSUE TITLE
onboardingConfigurationItem not called for index 0

### ISSUE THREAD

**Issue by ebenj** [Ramotion/paper-onboarding#38]
I'm using your demo code and trying to make the image full screen and send it to the background.

In ViewController -> onboardingConfigurationItem I have remove the current constrains and added new ones for the image to have full size.

Problem is that it is not working for the first (initial screen). But if I change to screen 2 and go back to initial screen then the method is called and the image is full size.

Any idea why this is happening?

**Comment by imadeit** [comment]
+1

**Comment by matiasgualino** [comment]
+1

**Comment by Daniel-Reiling** [comment]
+1

**Comment by luckycherry** [comment]
+111111

**Comment by ikolpachkov** [comment]
Just setup `delegate` property before `dataSource`
