### ISSUE TITLE
Button "skip" in example not showing

### ISSUE THREAD

**Issue by davidasimov** [Ramotion/paper-onboarding#43]
HI! The Button "skip" in example not showing. 
There is the lines:
// Uncomment next line to setup `PaperOnboarding` from code:
// setupPaperOnboardingView()

When I uncomment it "skip" button in example not showing.

**Comment by Mahdimm** [comment]
I have same problem

**Comment by Soulmastermobile** [comment]
onboarding.bringSubview(toFront: skipButton)
