### ISSUE TITLE
currentIndex() function not working

### ISSUE THREAD

**Issue by sara2869** [Ramotion/paper-onboarding#48]
Hi, I create a "Next" button and want go to next page when user clicked on it, I used below code for button action but not working:
```
@IBAction func btnNextClick(_ sender: Any) {
        let index = onboardingView.currentIndex + 1
        onboardingView.currentIndex(index, animated: false)
    
    }
```
What should i do? tnx

**Comment by ikolpachkov** [comment]
For me now it works fine, please reopen if needed (and/or provide more information)
