### ISSUE TITLE
Cannot convert return expression of type

### ISSUE THREAD

**Issue by perteraul** [Ramotion/paper-onboarding#50]
I'm having this error thrown out when trying to set up paper_onboarding from code, at the end of return `onboardingItemAtIndex` [index]

Cannot convert return expression of type '(Image, String, String, Image, UIColor, UIColor, UIColor, UIFont, UIFont)' (aka '(UIImage, String, String, UIImage, UIColor, UIColor, UIColor, UIFont, UIFont)') to return type 'OnboardingItemInfo' (aka '(imageName: String, title: String, description: String, iconName: String, color: UIColor, titleColor: UIColor, descriptionColor: UIColor, titleFont: UIFont, descriptionFont: UIFont)')

**Comment by DarkInnocence** [comment]
I am having the same error, moreover even if you explicitly typecast it, the app will crash as soon as you scroll to the next Onboarding view

**Comment by kornhera** [comment]
@perteraul Follow this format and it will work. I do however have the same issue as @DarkInnocence :/  return [(imageName: UIImage, title: "title", description: "description", iconName: UIImage , color: backgroundColorOne, titleColor: UIColor.white, descriptionColor: UIColor.white, titleFont: titleFont, descriptionFont: descirptionFont)][index]﻿

**Comment by JustinBobo** [comment]
I'm getting this error after updating to 3.0.5.

**Comment by Conoize** [comment]
I am getting the same error of perteraul on swift 4.0.3 :/

**Comment by kornhera** [comment]
I don’t remember what this is working on. Can you give me more info?

**Comment by Conoize** [comment]
okay error says, Cannot convert return expression of type '(UIImage, String, String, UIImage, UIColor, UIColor, UIColor, UIFont, UIFont)' to return type 'OnboardingItemInfo'

code is
<img width="1118" alt="screen shot 2018-05-17 at 10 22 57 pm" src="https://user-images.githubusercontent.com/25486632/41378169-3f812aa8-6f2c-11e8-96e6-0c66a283163b.png">
: 

> func onboardingItem(at index: Int) -> OnboardingItemInfo {
        
        let BGOne = #colorLiteral(red: 0.4062895179, green: 0.2437506914, blue: 0.06659346819, alpha: 1)
        let BGTwo = #colorLiteral(red: 0.3098039329, green: 0.01568627544, blue: 0.1294117719, alpha: 1)
        let BGThree = #colorLiteral(red: 0.9983721375, green: 0.9353169799, blue: 0.7877422571, alpha: 1)
        let textColor = #colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
        
        let titleFont = UIFont(name: "AvenirNext-Bold", size: 18)!
        let descFont = UIFont(name: "AvenirNext-Regular", size: 14)!
        
        
        return  [(#imageLiteral(resourceName: "illustration"), "Beer", "Beer is Awesome.", #imageLiteral(resourceName: "active"), BGOne , textColor, textColor, titleFont, descFont),
                 (#imageLiteral(resourceName: "post-1"), "Post", "Post is more Awesome.", #imageLiteral(resourceName: "active"), BGTwo , textColor, textColor, titleFont, descFont),
                 (#imageLiteral(resourceName: "card-1"), "Card", "Card is Awesome.", #imageLiteral(resourceName: "active"), BGThree , textColor, textColor, titleFont, descFont)][index]
    }

**Comment by Conoize** [comment]
please ignore the first image

**Comment by Conoize** [comment]
okay, error says : Cannot convert return expression of type '(UIImage, String, String, UIImage, UIColor, UIColor, UIColor, UIFont, UIFont)' to return type 'OnboardingItemInfo'
<img width="847" alt="screen shot 2018-06-13 at 5 06 49 pm" src="https://user-images.githubusercontent.com/25486632/41378308-b64b0fa0-6f2c-11e8-8bfe-4154990875a4.png">

**Comment by kornhera** [comment]
The error I think is with the image. Drag and drop it into the code don’t
type the address to it.

**Comment by Conoize** [comment]
okay, thank you!, working on it!

**Comment by Conoize** [comment]
:/ Nope, still the same problem, I even checked the onboarding item info "go to definition" to see what this method looks for in the return function, and matched with what I had, everything matches but still the same issue

**Comment by otbox21** [comment]
Did you happen to get it working, @Conoize ?

I'm having the same issue.  When I was working through the demo, I remember getting this, but I somehow fixed it.  Now, trying to put it in my app, I'm stuck again!

**Comment by Conoize** [comment]
Nope still working on it, but I got a possible solution here , if it works I'll share it with you! :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by otbox21** [comment]
thanks, same!

**Comment by Conoize** [comment]
yeah I fixed already the error of the uiimage but now it doesn't show up 😞That's the only thing that remains, here is the code:



extension DemoScreen: PaperOnboardingDataSource {

    func onboardingItemsCount() -> Int {

        return 1

    }



    func onboardingItem(at index: Int) -> OnboardingItemInfo {

//        let bgOne = #colorLiteral(red: 0.2196078449, green: 0.007843137719, blue: 0.8549019694, alpha: 1)

//        let bgTwo = #colorLiteral(red: 0.5725490451, green: 0, blue: 0.2313725501, alpha: 1)

//        let bgThree = #colorLiteral(red: 0.4062895179, green: 0.2437506914, blue: 0.06659346819, alpha: 1)

//

//        let textColor = #colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)

//        let titleFont = UIFont(name: "HelveticaNeue-Bold", size: 18)!

//        let descFont = UIFont(name: "HelveticaNeue-Bold", size: 14)!

//

//        return [(#imageLiteral(resourceName: "illustration"), "Beer", "Beer is awesome!", #imageLiteral(resourceName: "active"), bgOne, textColor, textColor, titleFont, descFont)][0]



        let onBoardItem: OnboardingItemInfo = OnboardingItemInfo(informationImage: UIImage(named: "illustration")!, title: "PVG", description: "Beer is Awesome!", pageIcon: UIImage(named: "active")!, color:  colorLiteral(red: 1, green: 0.8323456645, blue: 0.4732058644, alpha: 1), titleColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), descriptionColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), titleFont: UIFont(name: "AvenirNext-Medium", size: 18)!, descriptionFont: UIFont(name: "AvenirNext-Regular", size: 14)!)



        let onBoardItem2: OnboardingItemInfo = OnboardingItemInfo(informationImage: UIImage(named: "card-1")!, title: "PVG", description: "Card is Awesosome!", pageIcon: UIImage(named: "active")!, color:  colorLiteral(red: 0.4666666687, green: 0.7647058964, blue: 0.2666666806, alpha: 1), titleColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), descriptionColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), titleFont: UIFont(name: "AvenirNext-Medium", size: 18)!, descriptionFont: UIFont(name: "AvenirNext-Regular", size: 14)!)



        let onBoardItem3: OnboardingItemInfo = OnboardingItemInfo(informationImage: UIImage(named: "post-1")!, title: "PVG", description: "Let's Personalize Your Experience!", pageIcon: UIImage(named: "active")!, color:  colorLiteral(red: 0.4062895179, green: 0.2437506914, blue: 0.06659346819, alpha: 1), titleColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), descriptionColor:  colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0), titleFont: UIFont(name: "AvenirNext-Medium", size: 18)!, descriptionFont: UIFont(name: "AvenirNext-Regular", size: 14)!)





        return [onBoardItem, onBoardItem2, onBoardItem3][index]

    }



    func onboardingDidTransitonToIndex(_ index: Int) {

        if index == 2 {

            doneBtn.isHidden = false

        }

    }



    func onboardingWillTransitonToIndex(_ index: Int) {

        if index != 2 {

            if doneBtn.isHidden == false {

                doneBtn.isHidden = true

            }

        }

    }



    func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {



    }





}

________________________________

**Comment by otbox21** [comment]
I think I'm onto something here.  I think we may need to go back to paper-onboarding 3.0.1.  

I noticed in your code and my problematic code have this, 

![screen shot 2018-06-19 at 3 43 00 pm](https://user-images.githubusercontent.com/28899386/41620373-7b0c17fe-73d7-11e8-8cd8-6b0cc5d5192b.png)

...whereas the code I got working seemed to use a slightly different function
![screen shot 2018-06-19 at 3 44 34 pm](https://user-images.githubusercontent.com/28899386/41620442-bd1547f6-73d7-11e8-86d0-baba7eccbb31.png)


Also, I'm a novice, so hopefully I'm not breaking anything!   I'm going to try to make this work and will let you know.

**Comment by Conoize** [comment]
Yeah we could thell that we are in the same category 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by otbox21** [comment]
yes!  that did it!  You'll need to clean out the current version of the cocoapod that you have and install an older one.

https://www.natashatherobot.com/install-earlier-version-of-cocoapod/

https://stackoverflow.com/questions/13751147/remove-or-uninstall-library-previously-added-cocoapods

**Comment by Conoize** [comment]
Yeah! It worked over here too!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
