### ISSUE TITLE
Right-to-Left locale not working

### ISSUE THREAD

**Issue by talezion** [Ramotion/paper-onboarding#52]
Hi guys, can we add support for Right-to-Left languages please?

**Comment by ahmedsafadii** [comment]
same problem here

**Comment by 0ber** [comment]
Your could Fork this project and change the logic for UILabel in OnboardingContentViewItem https://github.com/Ramotion/paper-onboarding/blob/master/Source/OnboardingContentView/Item/OnboardingContantViewItem.swift#L19

**Comment by ahmedsafadii** [comment]
it's the circle issue <3

**Comment by anonrig** [comment]
@0ber why did you close this issue? this issue still persists
