### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mkocurek** [Ramotion/paper-onboarding#53]
Dear all,

I'm using Xcode 9 Beta 3 and as soon as I add "PaperOnboardingDelegate" to the ViewController Class and include onboardingView.delegate = self within the ViewDidLoad() I'll get the following error and the App crashes: 

2017-08-08 03:33:48.455340+0200 MyProject[7563:1139517] -[MyProject.ViewController onboardingConfigurationItem:index:]: unrecognized selector sent to instance 0x7f88d4602f70
2017-08-08 03:33:48.476036+0200 MyProject[7563:1139517] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MyProject.ViewController onboardingConfigurationItem:index:]: unrecognized selector sent to instance 0x7f88d4602f70'

Removing "onboardingView.delegate = self" will work but than the following functions are useless:

    func onboardingConfigurationItem(item: OnboardingContentViewItem, index: Int) {
    
    }
    
    func onboardingWillTransitionToIndex(index: Int) {
        if index == 1 {
            if self.getStartedButton.alpha == 1 {
                UIView.animate(withDuration: 0.2, animations: {
                    self.getStartedButton.alpha = 0
                })
            }
        }
    }
    
    func onboardingDidTransitionToIndex(index: Int) {
        if index == 2 {
            UIView.animate(withDuration: 0.4, animations: {
                self.getStartedButton.alpha = 1
            })
        }
    }

Any Ideas? Thanks for a quick reply.

BR,
Michael

**Comment by thephucit** [comment]
same issue :(

**Comment by thephucit** [comment]
@mkocurek 
Did you found solution for that?

**Comment by mkocurek** [comment]
nope, I didn't but gave up on paper-onboarding as I want more control over the objects.

**Comment by jchuter** [comment]
Exact same issue here.

**Comment by hallerman** [comment]
Same issue here - have been pulling what's let of my hair out.

**Comment by farzad789** [comment]
I have same issue 😔

**Comment by bhardman86** [comment]
Change 

func onboardingConfigurationItem(item: OnboardingContentViewItem, index: Int) {

}

to

func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {

}

**Comment by invinciible** [comment]
Same issue with me , Please help . I already spent so much time to learn

**Comment by monkeywithacupcake** [comment]
I'm getting an error here as well with the demo in Xcode 9
![screen shot 2017-09-25 at 17 55 38](https://user-images.githubusercontent.com/7316730/30800390-ce93b966-a21a-11e7-82dd-c133508d133f.png)

**Comment by benbahrenburg** [comment]
@monkeywithacupcake you need to do a cast see the below for an Xcode 9 example

```
  @objc func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {
    if let config = delegate as! PaperOnboardingDelegate? {
        config.onboardingConfigurationItem(item, index: index)
    }
  }  
```

**Comment by Rithprohos** [comment]
change to
`@objc func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {
`
`
}`
