### ISSUE TITLE
Styling Page Indicators

### ISSUE THREAD

**Issue by bakikocak** [Ramotion/paper-onboarding#55]
Hey everyone,

Firstly, that's a cool library to use. Thank you so much.

I was wondering if it is possible to style page indicator dots as I have to work on a white background. In my case, icon for active view is visible but the other indicators are not visible.

Thanks in advance.
Baki

**Comment by ikolpachkov** [comment]
Please check `func onboardingPageItemColor(at index: Int) -> UIColor` `PaperOnboardingDataSource` method
