### ISSUE TITLE
Unsupported Architectures error while archive validation process

### ISSUE THREAD

**Issue by bakikocak** [Ramotion/paper-onboarding#56]
I am using paper-onboarding on my new iOS app. Everything worked well and tested it on a real device. Although everything works perfectly I am getting the below error while trying to validate the app archive to be able to upload it to App Store. What could be the possible reason and solution for this?

> iTunes Store operation failed.
> Unsupported Architectures. The executable for myAppName.app/Frameworks/PaperOnboarding.framework contains unsupported architectures '[x86_64, i386]'.

**Comment by 0ber** [comment]
Do you use Carthage or Cocoapods ?

**Comment by bakikocak** [comment]
Sorry for lack of information. I use Carthage.

**Comment by bakikocak** [comment]
I found the solution on Carthage github repo (https://github.com/Carthage/Carthage). Adding what should be done in case that someone else also experiences this problem.

On your application targets’ “Build Phases” settings tab, click the “+” icon and choose “New Run Script Phase”. Create a Run Script in which you specify your shell (ex: /bin/sh), add the following contents to the script area below the shell:

/usr/local/bin/carthage copy-frameworks

Add the paths to the frameworks you want to use under “Input Files”, e.g.:
```
$(SRCROOT)/Carthage/Build/iOS/Result.framework
$(SRCROOT)/Carthage/Build/iOS/ReactiveSwift.framework
$(SRCROOT)/Carthage/Build/iOS/ReactiveCocoa.framework
```

Add the paths to the copied frameworks to the “Output Files”, e.g.:

```
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Result.framework
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/ReactiveSwift.framework
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/ReactiveCocoa.framework
```
