### ISSUE TITLE
any plan support xcode 9 ?

### ISSUE THREAD

**Issue by dopefaceee** [Ramotion/paper-onboarding#58]
got some errors when build project

**Comment by francisjervis** [comment]
Try setting your project to build using the Swift 3.2 compiler until the project is updated.

**Comment by dopefaceee** [comment]
yes but i got this an error https://imgur.com/a/gp8wq

**Comment by francisjervis** [comment]
After running pod update I have this too. @MaTriXy's fork works with Swift 4, change your podfile to 
````
pod 'paper-onboarding', :git => 'git@github.com:MaTriXy/paper-onboarding'
````
until the PRs are added here.

**Comment by dopefaceee** [comment]
thanks @francisjervis it's help me a lot

**Comment by ZenunVee** [comment]
I changed my podfile to this but still get this error? :/

**Comment by dopefaceee** [comment]
what is your error @ZenunVee  ?
