### ISSUE TITLE
Library Is Broken In Swift 4

### ISSUE THREAD

**Issue by a3ml** [Ramotion/paper-onboarding#62]
[https://imgur.com/a/n3JXK](url)

**Comment by digidhamu** [comment]
@c0reAmmar https://imgur.com/a/n3JXK is not found as I am getting 404 error. Please advise.

**Comment by adrianod1as** [comment]
Probably it is broken by the erros which the following PRs solve:

#60  // this one in particular is affecting my app

#61

**Comment by digidhamu** [comment]
Any idea when would this be fixed? However, I have commented this line that causes an error
`delegate?.onboardingConfigurationItem(item, index: index)` in `PaperOnboarding.swift`

**Comment by aznelite89** [comment]
delegate?.onboardingConfigurationItem(item, index: index) having an error :- Value of type 'AnyObject' has no member 'on boardingConfigurationItem().  **(Swift 4)**

**Comment by ahsanlakhani** [comment]
delegate?.onboardingConfigurationItem(item, index: index) having an error :- Value of type 'AnyObject' has no member 'on boardingConfigurationItem()

Kindly fix this please!

**Comment by lexuanquynh** [comment]
I think you should use any xcode version
