### ISSUE TITLE
Reposition of title, description and image

### ISSUE THREAD

**Issue by Sub-Zero-1** [Ramotion/paper-onboarding#65]
Hi. Is there a possiblity to reposition the items?

I would like to have the title at the top, the image in the center and the description at the bottom. 
To reposition the items should be a "must" for a library like this, but I cant see where to change. 

thanks!

**Comment by 0ber** [comment]
Reposition is not implemented, but you can create fork and change layout in this file https://github.com/Ramotion/paper-onboarding/blob/master/Source/OnboardingContentView/Item/OnboardingContantViewItem.swift
