### ISSUE TITLE
Copying sources folder doesn't work.

### ISSUE THREAD

**Issue by Dershowitz011** [Ramotion/paper-onboarding#7]
says use of undeclared type to anything that i want to use in my project.

**Comment by Dershowitz011** [comment]
Workaround is copy all the files individually to your project and then add them to a new group. Works that way.

**Comment by highthem** [comment]
still an issue!
<img width="1104" alt="capture d ecran 2016-06-01 a 12 01 09" src="https://cloud.githubusercontent.com/assets/2728100/15705719/bd377108-27f0-11e6-9328-4afb8941300e.png">

**Comment by vindicatesociety** [comment]
+1 
still an issue! 
swift2.2 tag 1.1.4

<img width="325" alt="screen shot 2016-09-25 at 12 21 47 pm" src="https://cloud.githubusercontent.com/assets/13971059/18817644/ab672312-831a-11e6-977d-6222aaa7298e.png">
