### ISSUE TITLE
Contextual type 'OnboardingItemInfo' cannot be used with array literal

### ISSUE THREAD

**Issue by carolinemcqueen** [Ramotion/paper-onboarding#72]
I'm trying to add content as per the instructions, but I get the following error:

Contextual type 'OnboardingItemInfo' (aka '(imageName: UIImage, title: String, description: String, iconName: UIImage, color: UIColor, titleColor: UIColor, descriptionColor: UIColor, titleFont: UIFont, descriptionFont: UIFont)') cannot be used with array literal

**Comment by carolinemcqueen** [comment]
Never mind. Solved it!

**Comment by otbox21** [comment]
mmmm...how?  Thanks!

**Comment by G-Vishal** [comment]
Whats the Solution ?
