### ISSUE TITLE
Receiving Error on Swift 4

### ISSUE THREAD

**Issue by anthonysaltarelli** [Ramotion/paper-onboarding#73]
Every time I try to declare an OnboardingItemInfo instance, I get the error: 

`'OnboardingItemInfo' initializer is inaccessible due to 'internal' protection level`

Only happened after I updated to most recent build.

**Comment by ghost** [comment]
Having the same issue

**Comment by sudovinh** [comment]
What was the fix to this issue?

**Comment by lucas-ferreira-machado** [comment]
Add the init in OnboardingItemInfo struct will fix it. @RamotionDev If you agree I can open a Pull Request for it.

public struct OnboardingItemInfo {
    public let informationImage: UIImage
    public let title: String
    public let description: String
    public let pageIcon: UIImage
    public let color: UIColor
    public let titleColor: UIColor
    public let descriptionColor: UIColor
    public let titleFont: UIFont
    public let descriptionFont: UIFont
    
    public init(informationImage: UIImage,title: String,description: String,pageIcon: UIImage,color: UIColor,titleColor: UIColor,descriptionColor: UIColor,titleFont: UIFont, descriptionFont: UIFont) {
        self.informationImage = informationImage
        self.title = title
        self.description = description
        self.pageIcon = pageIcon
        self.color = color
        self.titleColor = titleColor
        self.descriptionColor = descriptionColor
        self.titleFont = titleFont
        self.descriptionFont = descriptionFont
    }
}
