### ISSUE TITLE
Expression type '[Any]' is ambiguous without more context

### ISSUE THREAD

**Issue by onurgenes** [Ramotion/paper-onboarding#74]
When compiling with Xcode 9.3 it throws "Expression type '[Any]' is ambiguous without more context"
error.

**Comment by vjyanand** [comment]
@onurgenes on which line?

**Comment by redubr** [comment]
@vjyanand PageView.swift line 70

**Comment by StephenClarkApps** [comment]
I have the same

**Comment by pjcs2** [comment]
same here

**Comment by StephenClarkApps** [comment]
69-76 can become something like:
      let testing:[(NSLayoutAttribute, Int)] =  [(NSLayoutAttribute.left, 0), (NSLayoutAttribute.right, 0), (NSLayoutAttribute.bottom, Int(bottomConstant))]
      
        // add constraints
      for (attribute, const) in testing {
            (view, pageView) >>>- {
                $0.constant = CGFloat(const)
                $0.attribute = attribute
                return
            }
        }

**Comment by coolirisroto** [comment]
was solved?

**Comment by StephenClarkApps** [comment]
This was merged I believe, just not auto-closed due to the comment structure.

**Comment by StephenClarkApps** [comment]
should have been " Fixes #74 "

**Comment by onurgenes** [comment]
I will try the merge.If it's not working, I will reopen this issue.
