### ISSUE TITLE
Paper onboarding landscape issues 

### ISSUE THREAD

**Issue by bugbot7000** [Ramotion/paper-onboarding#77]
Layout issues in landscape mode on most iPhones 
<img width="632" alt="screen shot 2018-02-15 at 8 01 49 am" src="https://user-images.githubusercontent.com/32449543/36238141-9e9638e8-1226-11e8-83ad-378cb052779d.png">

if possible please upload a revision with ability to define title and description offset from page controller. or explain a workaround. thanks

**Comment by akmalshukri** [comment]
@96aman96 How your display the image ?
OnboardingItemInfo(informationImage: UIImage(named: "onboarding-logo")!,
                                   title: "Hotels",
                                   description: "All hotels and hostels are sorted by hospitality rating",
                                   pageIcon: UIImage(named: "onboarding-logo")!,
                                   color: UIColor(red: 0.40, green: 0.56, blue: 0.71, alpha: 1.00),
                                   titleColor: UIColor.white,
                                   descriptionColor: UIColor.white,
                                   titleFont: OnBoardViewController.titleFont,
                                   descriptionFont: OnBoardViewController.descriptionFont)

 I got error when do like this.

**Comment by yehe01** [comment]
I think the app disables landscape mode.
How did you manage to run it in landscape mode?

<img width="640" alt="screen shot 2018-05-07 at 10 11 20 am" src="https://user-images.githubusercontent.com/1256556/39679323-03b7b628-51df-11e8-91be-edb0fd6578c5.png">

**Comment by 0ber** [comment]
`Paper-Onboarding` is not supported landscape mode. You can make a fork and change the layout in `OnboardingContantViewItem`  https://github.com/Ramotion/paper-onboarding/blob/master/Source/OnboardingContentView/Item/OnboardingContantViewItem.swift
