### ISSUE TITLE
How can I change the image size ? and what is the default size ?

### ISSUE THREAD

**Issue by cs4alhaider** [Ramotion/paper-onboarding#78]
Hi
First, thank you for the amazing library 
I'm trying to make the image size bigger and I don't find how I could do that

**Comment by robmontesinos** [comment]
I was able to modify image sizes by using the onboardingConfigurationItem delegate method as suggested in https://github.com/Ramotion/paper-onboarding/issues/17

```
    func onboardingConfigurationItem(_ item: OnboardingContentViewItem, index: Int) {
        // config labels
        item.titleLabel?.numberOfLines = 0
        item.titleLabel?.lineBreakMode = .byWordWrapping
        item.descriptionLabel?.textAlignment = .left
        
        // allow for full width images
        if !onboardingItems[index].imageName.contains("ic_") {
            if let imageSize = item.imageView?.image?.size {
                item.informationImageWidthConstraint?.constant = imageSize.width
                item.informationImageHeightConstraint?.constant = imageSize.height
                item.setNeedsUpdateConstraints()
            }
        }
    }
```

I hope this helps. Salud!!

**Comment by otbox21** [comment]
In "OnboardingContantViewItem.swift", under the "paper-onboarding" folder in pods, there is

`    // add constratints
    for attribute in [NSLayoutConstraint.Attribute.width, NSLayoutConstraint.Attribute.height] {
      imageView >>>- {
        $0.attribute = attribute
        $0.constant  = 188
        return
      }
    }`

I just changed that 188 to 300, and I got this:

![screen shot 2018-06-27 at 4 25 44 pm](https://user-images.githubusercontent.com/28899386/41997755-e79e3e9c-7a26-11e8-8f02-fa15024dbc67.png)


Now, I'm pretty damn new to this stuff so if what I did was a terrible idea please let me know!

**Comment by bilaldrndo** [comment]
Yeah but now the first item is not resized?

**Comment by zpope0803** [comment]
Any fix or suggestion to the first item not getting resized?

**Comment by Suyogyart** [comment]
@bilaldrndo & @troutinsights I faced the same issue of first item not being resized initially, but is resized when I move to other indices and come back to first index again. 

For me solution was, assigning the delegate first then datasource in viewDidLoad.
Problem occurs when I do this: 
onboardingView.datasource = self
onboardingView.delegate = self

Solution:
onboardingView.delegate = self
onboardingView.datasource = self

Hope this is the case.
