### ISSUE TITLE
Actions to do once the walkthrough is over.

### ISSUE THREAD

**Issue by Dershowitz011** [Ramotion/paper-onboarding#8]
Once the walkthrough is done, the contents of the app should be shown. How do I do that? 
@ober01

**Comment by Dershowitz011** [comment]
Hello??

**Comment by thieu75** [comment]
Good question!

**Comment by masterfego** [comment]
I've created a button in the UIView, setUp constrains an forward to a segue if the user want to skip the intro.

**Comment by Dershowitz011** [comment]
@masterfego explain with a code sample please?

**Comment by Dershowitz011** [comment]
@Pakhaliuk @RamotionRussell  Help Please??

**Comment by Dershowitz011** [comment]
@Skogetroll

**Comment by 0ber** [comment]
@Dershowitz011 you can add "skip" UIButton on ViewController, and hide this viewController then tap on this button

**Comment by Dershowitz011** [comment]
@ober01 How do I add a  button when the last screen of walkthrough is presented? If i add a button, it'll be there for the entire view. :/

**Comment by 0ber** [comment]
I have added button in example

**Comment by Dershowitz011** [comment]
Perfect! Make this carthage compatible please. @ober01 Thanks.

**Comment by 0ber** [comment]
ok
