### ISSUE TITLE
unable add value in onboardingItemAtIndex.

### ISSUE THREAD

**Issue by harifsp** [Ramotion/paper-onboarding#80]
Cannot invoke initializer for type 'OnboardingItemInfo' with an argument list of type '(informationImage: Image, title: String, description: String, pageIcon: Image, color: UIColor, titleColor: UIColor, descriptionColor: UIColor, titleFont: UIFont, descriptionFont: UIFont)'

**Comment by akmalshukri** [comment]
anyone can solve this issue ? i also got same issue.

**Comment by akmalshukri** [comment]
please use imageName instead of informationImage and iconName instead of pageIcon.

**Comment by indiefr** [comment]
Please @RamotionDev update the documentation.
