### ISSUE TITLE
Swift @objc inference issue

### ISSUE THREAD

**Issue by ankitbadani** [Ramotion/paper-onboarding#82]
I get the @objc inference warning on Swift 4. When I set the @obj inference to Default in the Build Settings, the app crashes. When I turn it back to on, Paper Onboarding View Controller works fine. Any ideas as to why this is happening?

**Comment by 0ber** [comment]
Why do you need set the @objc ?

**Comment by ankitbadani** [comment]
Actually I was running on Swift 3 and then updated to Swift 4. I resolved the issue by running the pod update. Now everything is fine.
