### ISSUE TITLE
Remove parameters from initialisers that have no effect on view

### ISSUE THREAD

**Issue by yehe01** [Ramotion/paper-onboarding#83]
Setting pageViewRadius and pageViewSelectedRadius in the constructor below have no effect on the presented on-boarding view.

`public init(pageViewBottomConstant: CGFloat = 32, pageViewSelectedRadius: CGFloat = 22, pageViewRadius: CGFloat = 8) {...}`

The is because both values are provided by the default data source protocol implementation.
I would suggest removing these parameters from the constructor.

**Comment by 0ber** [comment]
thanks for the nice catch
