### ISSUE TITLE
Skip Button is throwing nil

### ISSUE THREAD

**Issue by Asinox** [Ramotion/paper-onboarding#84]
Hello guys, this thing is too simple but, i can't see it right now, i tried with re-doing the connections, and nothing changes.

The skip button is throwing nil

```
@IBOutlet weak var skipButton: UIButton!

override func viewDidLoad() {
        super.viewDidLoad()
        
        setupPaperOnboardingView()
        
        //view.bringSubview(toFront: skipButton)

    }
```

```//view.bringSubview(toFront: skipButton)``` Here is the problem

Any idea?

Thanks!

**Comment by 0ber** [comment]
`SkipButton` is not of part of `PaperOnboarding`. You can add any UI element on `ViewController` above `PaperOnboarding`

**Comment by otbox21** [comment]
@Asinox - this problem randomly popped up for me.  did you figure it out and do you remember the solution?
