### ISSUE TITLE
onboardingConfigurationItem

### ISSUE THREAD

**Issue by mauricekraus** [Ramotion/paper-onboarding#86]
is there a reason why onboardingConfigurationItem is not called on an initial call?

**Comment by JustinBobo** [comment]
I'm also wondering this

**Comment by JustinBobo** [comment]
If you initialize the PaperOnboarding view programmatically, onboardingConfigurationItem is called at initialization. However, if you initialize via the storyboard, it's not called at initialization.

**Comment by 0ber** [comment]
PaperOnboarding has not support storyboards
