### ISSUE TITLE
Changing the PageViewItem image on initialization

### ISSUE THREAD

**Issue by jboo1212** [Ramotion/paper-onboarding#87]
I desire something like this where the standard circles are replaced by the images themselves when unselected.  Is this possible in one of the delegate or data source methods?
![dishsnippet](https://user-images.githubusercontent.com/8954137/42055349-b654be9c-7acb-11e8-9029-4020f4d11a7d.PNG)

**Comment by Erik262** [comment]
Did you meanwhile solved that issue?

**Comment by jboo1212** [comment]
No.  I don't see how I can when that stuff is done in the background.

**Comment by 0ber** [comment]
Look the demo project, demo use this type of images https://github.com/Ramotion/paper-onboarding/blob/master/PaperOnboardingDemo/PaperOnboardingDemo/Assets.xcassets/Key.imageset/universal_Key.pdf
