### ISSUE TITLE
Fatal Error 'set DataSource' even if dataSource is set to self

### ISSUE THREAD

**Issue by Kanishka3** [Ramotion/paper-onboarding#88]
I have written the following code in viewDidLoad. Moreover, 'viewe' is a view connecting from storyboard. viewe is also connecting to dataSource in storyboard. 
`override func viewDidLoad() {
        super.viewDidLoad()
        let onboarding = PaperOnboarding(pageViewBottomConstant: 3)
        
       
        viewe.dataSource = self
        viewe.delegate = self
        
        onboarding.translatesAutoresizingMaskIntoConstraints = false
        viewe.addSubview(onboarding)
        for attribute: NSLayoutAttribute in [.left, .right, .top, .bottom] {
            let constraint = NSLayoutConstraint(item: onboarding,
                                                attribute: attribute,
                                                relatedBy: .equal,
                                                toItem: view,
                                                attribute: attribute,
                                                multiplier: 1,
                                                constant: 0)
             viewe.addConstraint(constraint)
        }

       
    }`

**Comment by amos-yau** [comment]
the author didn't mention, need to add "PaperOnboardingDataSource", as below

`class YourViewController: UIViewController, PaperOnboardingDataSource {`
