### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by AdieOlami** [Ramotion/paper-onboarding#90]
I am trying to implement on boarding with storyboard but after setting the uiview to class of PaperOnBoarding, I do not know where to proceed and I already connected the uiview to the Viewcontroller as datasource. What are the steps to take

**Comment by 0ber** [comment]
Paper-onboarding did not support storyboards. look at demo project https://github.com/Ramotion/paper-onboarding/blob/master/PaperOnboardingDemo/PaperOnboardingDemo/ViewController.swift#L49-L66
