### ISSUE TITLE
Argument labels '(itemsCount:)' do not match any available overloads

### ISSUE THREAD

**Issue by TimaShams** [Ramotion/paper-onboarding#95]
![image](https://user-images.githubusercontent.com/12412039/46592568-ce6a1d00-cacc-11e8-8e2f-b51edd60a088.png)

**Comment by 0ber** [comment]
Please look at the demo project: https://github.com/Ramotion/paper-onboarding/blob/master/PaperOnboardingDemo/PaperOnboardingDemo/ViewController.swift#L49-L66
