### ISSUE TITLE
'Attribute' is not a member type of 'NSLayoutConstraint'?

### ISSUE THREAD

**Issue by fukemy** [Ramotion/paper-onboarding#96]
Hi. I got this problem when build. plz help
```
  pod 'paper-onboarding'
```
swift 4.1 xcode 9

<img width="1680" alt="screen shot 2018-10-21 at 00 44 03" src="https://user-images.githubusercontent.com/8202437/47258773-74088d80-d4ca-11e8-8ebf-446a546fe2d0.png">

**Comment by 0ber** [comment]
you need to update swift to 4.2 or use previous lib version `pod 'paper-onboarding, ~> 4.1.0`
