### ISSUE TITLE
file was built for x86_64 which is not the architecture being linked (arm64): 

### ISSUE THREAD

**Issue by aaronjosephm** [Ramotion/paper-onboarding#98]
I'm seeing this error when trying to run my project with the PaperOnboarding.framework on my iOS device:

".../PaperOnboarding, file was built for x86_64 which is not the architecture being linked (arm64): /(mypath)/PaperOnboarding"

The app works on the simulator, so I thought I might fix the issue by changing the Valid architecture list, but the list has arm64 as a valid architecture in my build settings. Any idea how to fix this?

Also, I'm using Carthage.

**Comment by igork-ramotion** [comment]
I've checked current version it works fine with Carthage, so will close issue
